
* half girlfriend内容概要

年轻而又贫穷的男主（为了叙述方便，下文就叫他刘能吧）因为他的体育特长，拿到了印度当地很有名的大学的录取通知书。在上学期间，通过篮球结实了同样是篮球队的白富美女主（为了叙述方便，下文就叫她英子），两人进场一起上课，一起打篮球。年轻的刘能一直想着和英子进一步发展，但是年轻的英子想的都是诗和远方，她认为两人的感情应该是很纯洁的。每当刘能有想法的时候，都会被英子以各种借口躲过。

后来英子生日派对，邀请了刘能。在派对上，刘能得知英子还有一个远方的亲戚在最求着英子（暂时叫他阿光吧）。年轻的阿光家住伦敦，家里很有钱，英子的父母极力撮合她和阿光交往，希望他们尽快结婚。这让刘能很不是滋味。终于在一次争吵后，英子和刘能断绝了来往。没过多久，英子答应了阿光的求婚，退了学，搬去伦敦居住。

刘能从名牌大学毕业后，放弃了国际打银行的工作，回到落后的家乡。帮助母亲运营当地的学校。因为刘能的家乡是个非常落后的地方，学校连厕所也没有，整个学校算上他们母子，也就四个人。终于有一天，当地政府官员说比尔盖茨可能要来印度视察，他有自己的慈善基金，可以帮助落后地区发展。刘能喜出望外，但是比尔盖茨是个美国人，要用英文做演讲，说服盖茨来资助他们的学校。刘能比较退却了，因为虽然他读的大学是全英文的，但是他的英文依旧不是很好，更别说演讲了。所以考虑再三，他决定利用周末的时间，到省城里去学英语，为此他报了一个英语速成班。

一天，准备去上课的刘能在一家酒店碰到了英子。交谈得知英子已经离婚了。刘能一想上天对我真好，这是好机会呀。然后周末经常忘英子这里跑。英子经历了一次失败的婚姻后，想想这刘能也还不错，两人一拍即合，关系甚是融洽。刘能也退了英语班，由英子专门辅导，效果很不错。

在盖茨来之前，英子去了刘能办的学校游玩，碰到了刘能的母亲。她母亲对英子离过一次婚而感到十分不满。希望她能离开刘能。英子很伤心。在盖茨来那天，刘能的演讲很成功，盖茨的基金会当场宣布会资助这所学校。当刘能想和英子分享这份喜悦的时候，发现英子已经走了。并留下了一封信，信中说她已经得了肺癌，没几个月能活了。她准备去世界各地游玩一圈，希望刘能好好办这个学校，把她忘了。刘能很伤心。

两年后，之前英子租房的房东打给刘能电话，说他的柜子里还有一本英子的日记，让他去拿一下。看了日记刘能才知道，英子是在骗自己。她根本就没有得肺癌。然后刘能决定去找英子。他通过各种线索，发现英子出过了，去了美国。然后刘能回忆起，英子一直有一个音乐梦，希望在纽约的酒吧里驻唱。然后刘能通过基金会的关系，去纽约三个月，去寻找英子。

三个月中，刘能差不多快走遍了纽约所有的酒吧，还是没有找到。终于在要离开的前一天晚上，找到了英子。两人都很激动，都说再也不分开了。最后刘能把英子拐回了老家，当了音乐老师，两人快乐的生活在一起了。全剧终。
